---
author: "Ashish"
date: "`r Sys.Date()`"
output: html_document
params:
  statnet_graph_file: FALSE
title: "ERGM (`r stringr::str_extract(params$statnet_graph_file, '[0-9]+')` `r stringr::str_extract(params$statnet_graph_file, 'positive|negative|neutral')` )"
---


```{r}
if(!require(statnet)) install.packages("statnet")
if(!require(ergm)) install.packages("ergm")
if(!require(stringr)) install.packages("stringr")
library(statnet)
library(stringr)
library(ergm)
```

```{r}
# stringr::str_extract(params$statnet_graph_file, '[0-9]+') stringr::str_extract(params$statnet_graph_file, 'positive|negative|neutral')
```


# Fit ERGM
```{r}
# graph_fname <- file.path("data","proc","statnetGraphs",params$statnet_graph_file)
# print(graph_fname)
g <- readRDS(params$statnet_graph_file)
fit <- ergm(
   g ~ edges + transitiveweights(),
  reference = ~Unif(0,1),
  response = "weight",
  control = list(MCMLE.termination="Hotelling")
)
saveRDS(fit, file=paste0(params$statnet_graph_file, ""))
```


# Summarize ERGM
```{r}
summary(fit)
```

